name: codegen
on: workflow_dispatch

permissions:
  contents: write

jobs:
  codegen:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          fetch-depth: 0
          submodules: 'true'
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Codegen
        run: |
          find .  -name "*.cs" -type f -delete # remove all old files
          python codegen.py # generate new
      - name: Create PR
        id: generate-grpc
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          branch: db-dotnet-genproto/autopr
          delete-branch: true
          commit-message: 'Update grpc methods'
          title: 'Update grpc methods'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
#          assignees:
#          reviewers: