name: codegen
on:
  workflow_dispatch:
    inputs:
      checkout:
        description: 'Branch or commit of ydb-api-protos'
        required: true
        default: 'master'
        type: string
        

permissions:
  contents: write

jobs:
  codegen:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          fetch-depth: 0
          submodules: 'true'
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
          cd ydb-api-protos
          git checkout ${{ inputs.checkout }}
          cd ..
          today=$(date +%Y%m%d_%H%m)
      - name: Run Codegen
        run: bash .github/scripts/regenerate.sh
      - name: Create PR
        id: generate-grpc
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.YDB_PLATFORM_BOT_TOKEN_REPO }}
          branch: autopr/${{ inputs.checkout }}${{ env.today }}
          delete-branch: true
          commit-message: 'Update grpc methods'
          title: 'Update grpc methods'
          body: |
            Regenerate grpc methods
            - Auto-generated
          labels: |
            automated pr
#          assignees:
#          reviewers:
